---
abstract: 'Portable wrapper for OpenSSL Command'
author:
  - 'James F Wilkus <jfwilkus@cpan.org>'
build_requires:
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  File::ShareDir::Install: 0.06
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tiny-OpenSSL
requires:
  Capture::Tiny: 0
  Carp: 0
  Exporter: 0
  File::ShareDir: 0
  Moo: 0
  Moo::Role: 0
  Path::Tiny: 0
  Types::Standard: 0
  YAML::Tiny: 0
  base: 0
  perl: v5.8.4
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jfwilkus/Tiny-OpenSSL/issues
  homepage: https://github.com/jfwilkus/Tiny-OpenSSL
  repository: https://github.com/jfwilkus/Tiny-OpenSSL.git
version: 0.1.2
